REM INSERTING into DB2013_G14.COUNTRIES
SET DEFINE OFF;
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Soviet Union','URS');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Equatorial Guinea','GEQ');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Saint Kitts and Nevis','SKN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Bosnia and Herzegovina','BIH');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Madagascar','MAD');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Lebanon','LIB');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Syria','SYR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Seychelles','SEY');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Uruguay','URU');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Oman',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Thailand','THA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Namibia','NAM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Philippines','PHI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Moldova','MDA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Malawi',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Kiribati',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Lithuania','LTU');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Turkey','TUR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Pakistan','PAK');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('United States Virgin Islands',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Belarus','BLR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Ghana','GHA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('South Korea','KOR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Empire of Japan',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Samoa','SAM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Trinidad and Tobago','TRI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Sweden','SWE');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Solomon Islands','SOL');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('China','CHN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Sudan','SUD');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Niger','NIG');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Panama','PAN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('British Guiana',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Chad','CHA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('South Sudan',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Liberia',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Hungary','HUN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Laos','LAO');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Cameroon','CMR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Tuvalu','TUV');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Socialist Federal Republic of Yugoslavia',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Togo','TOG');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Botswana','BOT');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Burundi','BDI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Bhutan',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Canada','CAN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Norway','NOR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Brazil','BRA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Kazakhstan','KAZ');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Estonia','EST');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Poland','POL');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Rome',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Morocco','MAR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Belgium','BEL');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Cook Islands','COK');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Egypt','EGY');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Ukraine','UKR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Uganda','UGA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Saint Lucia','LCA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Holland',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Libya',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Independent Olympic Participants','IOP');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Burma','MYA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Malaysia','MAS');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Israel','ISR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Aruba','ARU');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Republic of Macedonia','MKD');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Spain','ESP');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('British Virgin Islands','IVB');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Bolivia','BOL');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Unified Team',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Commonwealth of Independent States',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Grenada','GRN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('India','IND');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Armenia','ARM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Jordan','JOR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Argentina','ARG');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Mexico','MEX');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Angola','ANG');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Côte d’Ivoire','CIV');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Cayman Islands','CAY');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Guinea','GUI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Virgin Islands',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Iraq','IRQ');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Kenya','KEN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('West Germany',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Haiti','HAI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Serbia and Montenegro',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Central African Republic','CAF');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Belize','BIZ');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Austria','AUT');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Denmark','DEN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Tajikistan','TJK');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Switzerland','SUI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Venezuela','VEN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Mongolia','MGL');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Uzbekistan','UZB');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Congo',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Comoros','COM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Czechoslovakia','TCH');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Vietnam','VIE');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Tunisia','TUN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('American Samoa',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Zimbabwe','ZIM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Rwanda','RWA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Guam','GUM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('El Salvador','ESA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Nauru','NRU');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Democratic Republic of the Congo',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Great Britain',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Nicaragua','NCA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Rhodesia',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('France','FRA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Georgia','GEO');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Cuba','CUB');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Russia','RUS');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Guinea-Bissau','GBS');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Bahrain','BRN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Sri Lanka','SRI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Saint Vincent and the Grenadines','VIN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Taiwan','TPE');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Barbados','BAR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Mauritius','MRI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('State of Palestine',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Guatemala','GUA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Guyana','GUY');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Nepal','NEP');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Suriname','SUR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Palau','PLW');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Marshall Islands','MHL');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Djibouti','DJI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Monaco','MON');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Yemen','YEM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Kingdom of Yugoslavia',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Bahamas','BAH');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Malta','MLT');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('New Zealand','NZL');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Eritrea','ERI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Vanuatu',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Qatar','QAT');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Paraguay','PAR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Finland','FIN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Saudi Arabia','KSA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Croatia','CRO');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Indonesia','INA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Ecuador','ECU');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Fiji','FIJ');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Mauritania','MTN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Papua New Guinea','PNG');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Maldives','MDV');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Netherlands Antilles','AHO');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Dominican Republic','DOM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Dominica','DMA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Portugal','POR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Palestinian Territories',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Swaziland','SWZ');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Tanzania','TAN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Timor-Leste','TLS');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Australia','AUS');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Ethiopia','ETH');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Federated States of Micronesia','FSM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Andorra','AND');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Czech Republic','CZE');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Germany','GER');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Honduras','HON');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Cyprus','CYP');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Liechtenstein','LIE');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Hong Kong','HKG');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Curaçao',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Jamaica','JAM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Cape Verde','CPV');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Bohemia',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Burkina Faso','BUR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Gambia','GAM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Yugoslavia',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Gabon','GAB');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Japan','JPN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Algeria','ALG');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Bulgaria','BUL');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Peru','PER');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Ireland','IRL');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Luxembourg','LUX');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Chile','CHI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Brunei','BRU');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Albania','ALB');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('United Arab Emirates','UAE');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Azerbaijan','AZE');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Kyrgyzstan','KGZ');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Italy','ITA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Lesotho','LES');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Netherlands','NED');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Costa Rica','CRC');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('South Africa','RSA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Singapore','SIN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('San Marino','SMR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Afghanistan','AFG');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Mozambique','MOZ');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Serbia','SRB');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Slovakia','SVK');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Cambodia','CAM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Latvia','LAT');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Iran','IRI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('England',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Sierra Leone',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Montenegro','MNE');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Palestinian territories',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Scotland',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Russian Empire',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Bermuda','BER');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('British West Indies',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Colombia','COL');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Iceland','ISL');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Australasia',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Benin','BEN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Zambia','ZAM');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Mixed team',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('North Korea','PRK');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Puerto Rico','PUR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Antigua and Barbuda','ANT');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Somalia',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Slovak Republic',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Tonga','TGA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('United Team of Germany','EUA');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('German Democratic Republic','GDR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Kuwait','KUW');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Turkmenistan',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Gold Coast',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Senegal','SEN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('São Tomé and Príncipe','STP');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Romania','ROU');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Mali','MLI');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Bangladesh','BAN');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Slovenia','SLO');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Estados Unidos',null);
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Greece','GRE');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('Nigeria','NGR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('United Kingdom','GBR');
Insert into DB2013_G14.COUNTRIES (NAME,IOC_CODE) values ('United States of America','USA');
