--------------------------------------------------------
--  DDL for Table GAMES
--------------------------------------------------------

  CREATE TABLE "DB2013_G14"."GAMES" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"NB_OF_COUNTRIES" NUMBER(*,0), 
	"NB_OF_EVENTS" NUMBER(*,0), 
	"NB_OF_ATHLETES" NUMBER(*,0), 
	"HOST_CITY" VARCHAR2(30 BYTE), 
	"HOST_COUNTRY" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DB_STUDENTS_2012" ;
