--------------------------------------------------------
--  File created - mercredi-mai-29-2013   
--------------------------------------------------------
@C:\Users\cgb\ATHLETES.sql
@C:\Users\cgb\COUNTRIES.sql
@C:\Users\cgb\DISCIPLINES.sql
@C:\Users\cgb\EVENTS.sql
@C:\Users\cgb\GAMES.sql
@C:\Users\cgb\MEDALS.sql
@C:\Users\cgb\PARTICIPANTS.sql
@C:\Users\cgb\SPORTS.sql
@C:\Users\cgb\ATHLETES_DATA_TABLE.sql
@C:\Users\cgb\COUNTRIES_DATA_TABLE.sql
@C:\Users\cgb\DISCIPLINES_DATA_TABLE.sql
@C:\Users\cgb\EVENTS_DATA_TABLE.sql
@C:\Users\cgb\GAMES_DATA_TABLE.sql
@C:\Users\cgb\MEDALS_DATA_TABLE.sql
@C:\Users\cgb\PARTICIPANTS_DATA_TABLE.sql
@C:\Users\cgb\SPORTS_DATA_TABLE.sql
@C:\Users\cgb\SYS_C00543093.sql
@C:\Users\cgb\SYS_C00543068.sql
@C:\Users\cgb\SYS_C00543113.sql
@C:\Users\cgb\SYS_C00543115.sql
@C:\Users\cgb\SYS_C00543071.sql
@C:\Users\cgb\SYS_C00543138.sql
@C:\Users\cgb\SYS_C00543129.sql
@C:\Users\cgb\SYS_C00543095.sql
@C:\Users\cgb\ATHLETES_CONSTRAINT.sql
@C:\Users\cgb\COUNTRIES_CONSTRAINT.sql
@C:\Users\cgb\DISCIPLINES_CONSTRAINT.sql
@C:\Users\cgb\EVENTS_CONSTRAINT.sql
@C:\Users\cgb\GAMES_CONSTRAINT.sql
@C:\Users\cgb\MEDALS_CONSTRAINT.sql
@C:\Users\cgb\PARTICIPANTS_CONSTRAINT.sql
@C:\Users\cgb\SPORTS_CONSTRAINT.sql
@C:\Users\cgb\DISCIPLINES_REFCONSTRAINT.sql
@C:\Users\cgb\EVENTS_REFCONSTRAINT.sql
@C:\Users\cgb\GAMES_REFCONSTRAINT.sql
@C:\Users\cgb\MEDALS_REFCONSTRAINT.sql
@C:\Users\cgb\PARTICIPANTS_REFCONSTRAINT.sql
