--------------------------------------------------------
--  Constraints for Table MEDALS
--------------------------------------------------------

  ALTER TABLE "DB2013_G14"."MEDALS" MODIFY ("MEDAL" NOT NULL ENABLE);
 
  ALTER TABLE "DB2013_G14"."MEDALS" MODIFY ("OLYMPICS" NOT NULL ENABLE);
 
  ALTER TABLE "DB2013_G14"."MEDALS" MODIFY ("SPORT" NOT NULL ENABLE);
 
  ALTER TABLE "DB2013_G14"."MEDALS" MODIFY ("DISCIPLINES" NOT NULL ENABLE);
 
  ALTER TABLE "DB2013_G14"."MEDALS" ADD PRIMARY KEY ("AID", "OLYMPICS", "COUNTRY", "SPORT", "DISCIPLINES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DB_STUDENTS_2012"  ENABLE;
 
  ALTER TABLE "DB2013_G14"."MEDALS" MODIFY ("AID" NOT NULL ENABLE);
 
  ALTER TABLE "DB2013_G14"."MEDALS" MODIFY ("COUNTRY" NOT NULL ENABLE);
