--------------------------------------------------------
--  Constraints for Table PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "DB2013_G14"."PARTICIPANTS" MODIFY ("AID" NOT NULL ENABLE);
 
  ALTER TABLE "DB2013_G14"."PARTICIPANTS" MODIFY ("COUNTRY" NOT NULL ENABLE);
 
  ALTER TABLE "DB2013_G14"."PARTICIPANTS" MODIFY ("OLYMPICS" NOT NULL ENABLE);
 
  ALTER TABLE "DB2013_G14"."PARTICIPANTS" MODIFY ("SPORT" NOT NULL ENABLE);
 
  ALTER TABLE "DB2013_G14"."PARTICIPANTS" ADD PRIMARY KEY ("AID", "OLYMPICS", "COUNTRY", "SPORT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DB_STUDENTS_2012"  ENABLE;
