--------------------------------------------------------
--  Ref Constraints for Table PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "DB2013_G14"."PARTICIPANTS" ADD FOREIGN KEY ("AID")
	  REFERENCES "DB2013_G14"."ATHLETES" ("AID") ENABLE;
 
  ALTER TABLE "DB2013_G14"."PARTICIPANTS" ADD FOREIGN KEY ("OLYMPICS")
	  REFERENCES "DB2013_G14"."GAMES" ("NAME") ENABLE;
 
  ALTER TABLE "DB2013_G14"."PARTICIPANTS" ADD FOREIGN KEY ("SPORT")
	  REFERENCES "DB2013_G14"."SPORTS" ("NAME") ENABLE;
 
  ALTER TABLE "DB2013_G14"."PARTICIPANTS" ADD FOREIGN KEY ("COUNTRY")
	  REFERENCES "DB2013_G14"."COUNTRIES" ("NAME") ENABLE;
