REM INSERTING into DB2013_G14.SPORTS
SET DEFINE OFF;
Insert into DB2013_G14.SPORTS (NAME) values ('Air sports');
Insert into DB2013_G14.SPORTS (NAME) values ('Alpine Skiing');
Insert into DB2013_G14.SPORTS (NAME) values ('Alpine skiing');
Insert into DB2013_G14.SPORTS (NAME) values ('American football');
Insert into DB2013_G14.SPORTS (NAME) values ('Archery');
Insert into DB2013_G14.SPORTS (NAME) values ('Archery ');
Insert into DB2013_G14.SPORTS (NAME) values ('Artistic gymnastics');
Insert into DB2013_G14.SPORTS (NAME) values ('Athletics');
Insert into DB2013_G14.SPORTS (NAME) values ('Australian rules football');
Insert into DB2013_G14.SPORTS (NAME) values ('BMX racing');
Insert into DB2013_G14.SPORTS (NAME) values ('Badminton');
Insert into DB2013_G14.SPORTS (NAME) values ('Bandy');
Insert into DB2013_G14.SPORTS (NAME) values ('Baseball');
Insert into DB2013_G14.SPORTS (NAME) values ('Basketball');
Insert into DB2013_G14.SPORTS (NAME) values ('Beach volleyball');
Insert into DB2013_G14.SPORTS (NAME) values ('Biathlon');
Insert into DB2013_G14.SPORTS (NAME) values ('Billiards');
Insert into DB2013_G14.SPORTS (NAME) values ('Bobsleigh');
Insert into DB2013_G14.SPORTS (NAME) values ('Boules');
Insert into DB2013_G14.SPORTS (NAME) values ('Bowling');
Insert into DB2013_G14.SPORTS (NAME) values ('Boxing');
Insert into DB2013_G14.SPORTS (NAME) values ('Boxing ');
Insert into DB2013_G14.SPORTS (NAME) values ('Budo');
Insert into DB2013_G14.SPORTS (NAME) values ('Canne de combat');
Insert into DB2013_G14.SPORTS (NAME) values ('Canoe Slalom');
Insert into DB2013_G14.SPORTS (NAME) values ('Canoe Sprint');
Insert into DB2013_G14.SPORTS (NAME) values ('Canoeing');
Insert into DB2013_G14.SPORTS (NAME) values ('Chess');
Insert into DB2013_G14.SPORTS (NAME) values ('Contract bridge');
Insert into DB2013_G14.SPORTS (NAME) values ('Cray Shooting');
Insert into DB2013_G14.SPORTS (NAME) values ('Cricket');
Insert into DB2013_G14.SPORTS (NAME) values ('Croquet');
Insert into DB2013_G14.SPORTS (NAME) values ('Cross Country Skiing');
Insert into DB2013_G14.SPORTS (NAME) values ('Cross country running');
Insert into DB2013_G14.SPORTS (NAME) values ('Cross-Country');
Insert into DB2013_G14.SPORTS (NAME) values ('Cross-Country Skiing');
Insert into DB2013_G14.SPORTS (NAME) values ('Cross-country Skiing');
Insert into DB2013_G14.SPORTS (NAME) values ('Cross-country skiing');
Insert into DB2013_G14.SPORTS (NAME) values ('Curling');
Insert into DB2013_G14.SPORTS (NAME) values ('Cycling');
Insert into DB2013_G14.SPORTS (NAME) values ('DanceSport');
Insert into DB2013_G14.SPORTS (NAME) values ('Diving');
Insert into DB2013_G14.SPORTS (NAME) values ('Dogsled racing');
Insert into DB2013_G14.SPORTS (NAME) values ('Dominican Republic');
Insert into DB2013_G14.SPORTS (NAME) values ('Dressage');
Insert into DB2013_G14.SPORTS (NAME) values ('Equestrian');
Insert into DB2013_G14.SPORTS (NAME) values ('Equestrian vaulting');
Insert into DB2013_G14.SPORTS (NAME) values ('Eventing');
Insert into DB2013_G14.SPORTS (NAME) values ('Fencing');
Insert into DB2013_G14.SPORTS (NAME) values ('Field handball');
Insert into DB2013_G14.SPORTS (NAME) values ('Field hockey');
Insert into DB2013_G14.SPORTS (NAME) values ('Figure Skating');
Insert into DB2013_G14.SPORTS (NAME) values ('Figure skating');
Insert into DB2013_G14.SPORTS (NAME) values ('Football');
Insert into DB2013_G14.SPORTS (NAME) values ('Freestyle Skiing');
Insert into DB2013_G14.SPORTS (NAME) values ('Freestyle skiing');
Insert into DB2013_G14.SPORTS (NAME) values ('Freestyle wrestling');
Insert into DB2013_G14.SPORTS (NAME) values ('Frisian handball');
Insert into DB2013_G14.SPORTS (NAME) values ('Gliding');
Insert into DB2013_G14.SPORTS (NAME) values ('Glima');
Insert into DB2013_G14.SPORTS (NAME) values ('Golf');
Insert into DB2013_G14.SPORTS (NAME) values ('Greco-Roman wrestling');
Insert into DB2013_G14.SPORTS (NAME) values ('Gymnastics');
Insert into DB2013_G14.SPORTS (NAME) values ('Handball');
Insert into DB2013_G14.SPORTS (NAME) values ('Hot air ballooning');
Insert into DB2013_G14.SPORTS (NAME) values ('Ice Hockey');
Insert into DB2013_G14.SPORTS (NAME) values ('Ice hockey');
Insert into DB2013_G14.SPORTS (NAME) values ('Ice stock sport');
Insert into DB2013_G14.SPORTS (NAME) values ('Jeu De Paume');
Insert into DB2013_G14.SPORTS (NAME) values ('Jeu de paume');
Insert into DB2013_G14.SPORTS (NAME) values ('Judo');
Insert into DB2013_G14.SPORTS (NAME) values ('Judo ');
Insert into DB2013_G14.SPORTS (NAME) values ('Karate');
Insert into DB2013_G14.SPORTS (NAME) values ('Korfball');
Insert into DB2013_G14.SPORTS (NAME) values ('Lacrosse');
Insert into DB2013_G14.SPORTS (NAME) values ('Lifesaving');
Insert into DB2013_G14.SPORTS (NAME) values ('Longue paume');
Insert into DB2013_G14.SPORTS (NAME) values ('Luge');
Insert into DB2013_G14.SPORTS (NAME) values ('Military patrol');
Insert into DB2013_G14.SPORTS (NAME) values ('Modern Pentathlon');
Insert into DB2013_G14.SPORTS (NAME) values ('Modern Pentathlon ');
Insert into DB2013_G14.SPORTS (NAME) values ('Modern pentathlon');
Insert into DB2013_G14.SPORTS (NAME) values ('Motorcycle racing');
Insert into DB2013_G14.SPORTS (NAME) values ('Motorsport');
Insert into DB2013_G14.SPORTS (NAME) values ('Mountain biking');
Insert into DB2013_G14.SPORTS (NAME) values ('Mountaineering');
Insert into DB2013_G14.SPORTS (NAME) values ('Netball');
Insert into DB2013_G14.SPORTS (NAME) values ('Nordic Combined');
Insert into DB2013_G14.SPORTS (NAME) values ('Nordic combined');
Insert into DB2013_G14.SPORTS (NAME) values ('Olympic trap');
Insert into DB2013_G14.SPORTS (NAME) values ('Orienteering');
Insert into DB2013_G14.SPORTS (NAME) values ('Paralympic alpine skiing');
Insert into DB2013_G14.SPORTS (NAME) values ('Paralympic nordic skiing');
Insert into DB2013_G14.SPORTS (NAME) values ('Pesäpallo');
Insert into DB2013_G14.SPORTS (NAME) values ('Pilota');
Insert into DB2013_G14.SPORTS (NAME) values ('Polo');
Insert into DB2013_G14.SPORTS (NAME) values ('Powerboating');
Insert into DB2013_G14.SPORTS (NAME) values ('Race walking');
Insert into DB2013_G14.SPORTS (NAME) values ('Rackets');
Insert into DB2013_G14.SPORTS (NAME) values ('Racquetball');
Insert into DB2013_G14.SPORTS (NAME) values ('Racquets');
Insert into DB2013_G14.SPORTS (NAME) values ('Rhythmic gymnastics');
Insert into DB2013_G14.SPORTS (NAME) values ('Road cycling');
Insert into DB2013_G14.SPORTS (NAME) values ('Road running');
Insert into DB2013_G14.SPORTS (NAME) values ('Roller hockey');
Insert into DB2013_G14.SPORTS (NAME) values ('Roller sport');
Insert into DB2013_G14.SPORTS (NAME) values ('Roque');
Insert into DB2013_G14.SPORTS (NAME) values ('Rowing');
Insert into DB2013_G14.SPORTS (NAME) values ('Rugby union');
Insert into DB2013_G14.SPORTS (NAME) values ('Sailing');
Insert into DB2013_G14.SPORTS (NAME) values ('Savate');
Insert into DB2013_G14.SPORTS (NAME) values ('Shooting');
Insert into DB2013_G14.SPORTS (NAME) values ('Shooting sports');
Insert into DB2013_G14.SPORTS (NAME) values ('Short Track Speed Skating');
Insert into DB2013_G14.SPORTS (NAME) values ('Short track speed skating');
Insert into DB2013_G14.SPORTS (NAME) values ('Show jumping');
Insert into DB2013_G14.SPORTS (NAME) values ('Skeleton');
Insert into DB2013_G14.SPORTS (NAME) values ('Ski Jumping');
Insert into DB2013_G14.SPORTS (NAME) values ('Ski jumping');
Insert into DB2013_G14.SPORTS (NAME) values ('Skijoring');
Insert into DB2013_G14.SPORTS (NAME) values ('Snowboarding');
Insert into DB2013_G14.SPORTS (NAME) values ('Snowboardng');
Insert into DB2013_G14.SPORTS (NAME) values ('Softball');
Insert into DB2013_G14.SPORTS (NAME) values ('Speed Skating');
Insert into DB2013_G14.SPORTS (NAME) values ('Speed skating');
Insert into DB2013_G14.SPORTS (NAME) values ('Speed skiing');
Insert into DB2013_G14.SPORTS (NAME) values ('Sport climbing');
Insert into DB2013_G14.SPORTS (NAME) values ('Squash');
Insert into DB2013_G14.SPORTS (NAME) values ('Sumo');
Insert into DB2013_G14.SPORTS (NAME) values ('Surfing');
Insert into DB2013_G14.SPORTS (NAME) values ('Swimming');
Insert into DB2013_G14.SPORTS (NAME) values ('Synchronized Swimming');
Insert into DB2013_G14.SPORTS (NAME) values ('Synchronized swimming');
Insert into DB2013_G14.SPORTS (NAME) values ('Table Tennis');
Insert into DB2013_G14.SPORTS (NAME) values ('Table tennis');
Insert into DB2013_G14.SPORTS (NAME) values ('Taekwondo');
Insert into DB2013_G14.SPORTS (NAME) values ('Team handball');
Insert into DB2013_G14.SPORTS (NAME) values ('Tennis');
Insert into DB2013_G14.SPORTS (NAME) values ('Track and field athletics');
Insert into DB2013_G14.SPORTS (NAME) values ('Track cycling');
Insert into DB2013_G14.SPORTS (NAME) values ('Trampoline');
Insert into DB2013_G14.SPORTS (NAME) values ('Triathlon');
Insert into DB2013_G14.SPORTS (NAME) values ('Tug of war');
Insert into DB2013_G14.SPORTS (NAME) values ('Volleyball');
Insert into DB2013_G14.SPORTS (NAME) values ('Water polo');
Insert into DB2013_G14.SPORTS (NAME) values ('Water skiing');
Insert into DB2013_G14.SPORTS (NAME) values ('Weightlifting');
Insert into DB2013_G14.SPORTS (NAME) values ('Wheelchair racing');
Insert into DB2013_G14.SPORTS (NAME) values ('Winter Pentathalon');
Insert into DB2013_G14.SPORTS (NAME) values ('Wrestling');
Insert into DB2013_G14.SPORTS (NAME) values ('Wrestling ');
Insert into DB2013_G14.SPORTS (NAME) values ('Wushu');
Insert into DB2013_G14.SPORTS (NAME) values ('athletics');
